project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Studious Pancake"
  author:
    - Joyce Robbins (jtr13)

  repo-url: https://github.com/jtr13/studious-pancake
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd


format:
  html:
    theme: superhero
    code-fold: true


